Quick fix for Linux i686 32-bit release build
VERBOSE (TEST) DETAILS:

OS: Ubuntu (i686 (32-bit))
selenium-webdriver (3.4.0)
Browser: Firefox (53.0 (32-bit))
geckodriver (0.14.0)

As of this commit:
https://github.com/mozilla/geckodriver/releases does not provide a link for a 32-bit linux release of the current 0.16.0 or older 0.15.0 builds.

0.14.0 is the last version of geckodriver that has had a successful release build, as seen here:
https://travis-ci.org/mozilla/geckodriver/builds

There seems to be a bug with geckodriver 0.14.0 sending marionette a null sessionId on initial connection, i.e:
capabilities:{“sessionId”:null } and/or possibly mishandling the valid sessionId to/from the webdriver.

Environment: running headless via selenium-webdriver, Xfvb, and firefox

The following error can be seen in debug mode while using geckodriver:
/usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:118:in `create_session': no sessionId in returned payload (Selenium::WebDriver::Error::WebDriverError)

The following errors can be seen when compiling geckodriver 0.16.0 with backtrace-sys 0.1.6 and 0.1.10:
          /usr/local/src/geckodriver-0.16.0/target/i686-unknown-linux-musl/release/deps/libbacktrace_sys-8ce76439c7b98c3c.rlib(dwarf.o): In function `dwarf_buf_error':
          dwarf.c:(.text.dwarf_buf_error+0x63): undefined reference to `__snprintf_chk'
          /usr/local/src/geckodriver-0.16.0/target/i686-unknown-linux-musl/release/deps/libbacktrace_sys-8ce76439c7b98c3c.rlib(dwarf.o): In function `read_uleb128':
          dwarf.c:(.text.read_uleb128+0x114): undefined reference to `__snprintf_chk'
          dwarf.c:(.text.read_uleb128+0x182): undefined reference to `__snprintf_chk'
          /usr/local/src/geckodriver-0.16.0/target/i686-unknown-linux-musl/release/deps/libbacktrace_sys-8ce76439c7b98c3c.rlib(dwarf.o): In function `read_uint16':
          dwarf.c:(.text.read_uint16+0xd1): undefined reference to `__snprintf_chk'
          /usr/local/src/geckodriver-0.16.0/target/i686-unknown-linux-musl/release/deps/libbacktrace_sys-8ce76439c7b98c3c.rlib(dwarf.o): In function `read_uint32':
          dwarf.c:(.text.read_uint32+0xf1): undefined reference to `__snprintf_chk'
          /usr/local/src/geckodriver-0.16.0/target/i686-unknown-linux-musl/release/deps/libbacktrace_sys-8ce76439c7b98c3c.rlib(dwarf.o):dwarf.c:(.text.read_uint64+0x179): more undefined references to `__snprintf_chk' follow
          collect2: error: ld returned 1 exit status

Quick fix notes for a successful 0.16.0 release build on 32-bit linux:
* Tested changes:
1) downgraded backtrace-sys from 0.1.10 to 0.1.5 with a successful release build
2) tested with backtrace-sys 0.1.6 without success and with same failure as 0.1.10

notes:
a) It can be deduced that the bug was introduced in changes made in backtrace-sys 0.1.6.
b) I left gcc 0.3.45 and libc 0.2.21 (backtrace-sys deps) as they were in geckodriver 0.16.0.
c) geckodriver 0.14.0 (uses backtrace-sys 0.1.5) and used gcc 0.3.42 and libc 0.2.20 as deps.

backtrace 0.3.0 and backtrace-sys 0.1.5 introduced here (Jan 30):
https://github.com/mozilla/geckodriver/commit/6c161a2fe3cff818bcb5cf30cee92256229926de

backtrace-sys changed from 0.1.5 to 0.1.10 here (Feb 24):
https://github.com/mozilla/geckodriver/commit/09231df3527c0c37f2cc2210072683d6d8cbdbf5

Hope this helps.